### ISSUE TITLE
Multiple tests failing

### ISSUE THREAD

**Issue by kiran-anand14** [kiran-anand14/transform#5]

**Comment by kiran-anand14** [comment]
TC_6, TC_7, TC_8, TC_9 are failing. Check their inputs, transformers and outputs - you will get the idea that why they are failing.

**Comment by mahekshah5858** [comment]
For TC_6 test case, output columns should be AA, BB, CC instead of A, B, C. Also the order of the output columns should start with SS,AA,BB,CC onwards

For TC_7 and TC_9 there is single digit mismatch in AA(TC_7) and AA, BB (TC_9) columns. It seems that python round uses bankers rounding algorithm for this rounding which will round 12.5 to 12 but 13.5 to 14. It will round to nearest even number. 

For TC_8 I can not see any changes in the output end expected output but still its Failing.

**Comment by kiran-anand14** [comment]
Thanks, corrected TC_6 expected output, it is passing now.

**Comment by kiran-anand14** [comment]
Don't agree to this - "It seems that python round uses bankers rounding algorithm for this rounding which will round 12.5 to 12 but 13.5 to 14". This understanding is wrong. Having said this, current output is acceptable. So, changed the expected output.

I agree for TC_8, it should work. I am also not sure why pandas.equals() functions is failing for empty data frames.

**Comment by mahekshah5858** [comment]
For reference:
https://docs.python.org/dev/library/functions.html#round

It was not the case with python 2 but for python 3 its bankers rounding algorith.
